### ISSUE TITLE
overwrite parameter = False in download methods should prevent downloading if file exists

### ISSUE THREAD

**Issue by kan-fu** [OceanNetworksCanada/api-python-client#41]
There are 4 ways to download data in onc client library: 

- `downloadArchivefile`
- `downloadDirectArchivefile`
- `downloadDataProduct` 
- `orderDataProduct`

Only `downloadDirectArchivefile` checks whether the file exists before the download. Others will download the data first, then check whether the file should be downloaded. This is a waste of bandwidth if the file size is big.

**Comment by aschlesin** [comment]
This is a good catch @kan-fu. I agree a check for existing files should be implemented in all download functions.
